### PR TITLE
Add Social Media page

### PR DESCRIPTION
**Pull request by xaur**

### CODE REVIEW

**Comment by Michae2xl** [comment]
Reddit - 

https://www.reddit.com/r/DecredCanada/
https://www.reddit.com/r/DecredCA/

MeetUp -

https://www.meetup.com/decredpdx/
https://www.meetup.com/San-Francisco-Decred-Meetup/
https://www.meetup.com/Chicago-Decred-Meetup/
https://www.meetup.com/Decred-NYC/
https://www.meetup.com/Decred-Washington-DC-Meetup-Group/
https://www.meetup.com/Decred-Polska/
https://www.meetup.com/Decred-Australia/
https://www.meetup.com/Decred/ - Vancouver

**Comment by xaur** [comment]
Nice, thanks @Michae2xl ! Added all, latest preview [here](https://github.com/decredcommunity/wiki/blob/socialmedia/wiki/social-media.md).

Questions:

1. why there are two Canadian subreddits? What's the difference? Is it useful to have both in that list?
2. why Vancouver got "Decred" in the URL and not "Decred-Vancouver" or something?

**Comment by 3lian** [comment]
Some adds to the list:
Facebook page Decred en Español: https://www.facebook.com/DecredESP
Facebook page Decred Argentina: https://www.facebook.com/DecredArg

Regarding these:
Spanish: https://t.me/DecredES >>> this is the TG group of Decred en Español
Spanish: https://t.me/Decred_ES {empty? obsolete?} >>> this is a user a created to moderate the group but in practice it is not used, I think we should delete it from the list in order to not create confusion. 

In the case of Instagram I have the account decred_es but I havent started populating it, maybe is better to wait for the account to have some traction before publishing it.

**Comment by xaur** [comment]
@3lian thanks for the clarifications, this resolves all existing todos.

I found https://t.me/DecredArg on the Arg Facebook page, added to Telegram section.

Agreed to wait with decred_es Instagram. I see an opportunity in Instagram, let me know when it should be included.

**Comment by xaur** [comment]
Merged in master. Thanks for all the feedback. Let's use another PR to update.

**Pull request closed without merging**
